### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by vringar** [WorksButNotTested/lightkeeper#1]
Hey,
I want to package this plugin in Nixpkgs, alongside a bunch of other Ghidra Plugins.
However, I have noticed that this Repo doesn't contain a `LICENSE` file and everything that is not part of the template doesn't have a license header.
Could you clarify the license situation, by adding a top level file?

**Comment by WorksButNotTested** [comment]
What license works for you? Happy with something pretty permissive.

**Comment by vringar** [comment]
Idk how mixed licensing works so I'd suggest just putting it under the same license as Ghidra itself, Apache 2.0
Does that work for you?

**Comment by WorksButNotTested** [comment]
Sounds good. Do you have time to PR the necessary changes?
